[package]
name = "ultimate-kissing-simulator"
version = "0.1.0"
edition = "2021"

[dependencies]
macroquad = "0.4"

[package.metadata.android]
assets = "assets/"
[package.metadata.android.activity_attributes]
"android:exported" =  "true"
